// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2pasouopLHMOVMqOBEXWIzsSvAV_wYl8',
    appId: '1:612896768921:web:9c21db5d2ade89b3d00908',
    messagingSenderId: '612896768921',
    projectId: 'thecity-b0b9e',
    authDomain: 'thecity-b0b9e.firebaseapp.com',
    storageBucket: 'thecity-b0b9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rd1VI1ZGOPlYtPWttr0Ise4Xz07Q028',
    appId: '1:612896768921:android:cf807a1a1eb28135d00908',
    messagingSenderId: '612896768921',
    projectId: 'thecity-b0b9e',
    storageBucket: 'thecity-b0b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmR4o9XPwenY7NGFi_OKBwNbyhL0dVxyc',
    appId: '1:612896768921:ios:ad03dc3aa53ce715d00908',
    messagingSenderId: '612896768921',
    projectId: 'thecity-b0b9e',
    storageBucket: 'thecity-b0b9e.appspot.com',
    iosClientId: '612896768921-d0kcq2up03r534grgkmcfofvu1l5h0nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.theCity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmR4o9XPwenY7NGFi_OKBwNbyhL0dVxyc',
    appId: '1:612896768921:ios:ad03dc3aa53ce715d00908',
    messagingSenderId: '612896768921',
    projectId: 'thecity-b0b9e',
    storageBucket: 'thecity-b0b9e.appspot.com',
    iosClientId: '612896768921-d0kcq2up03r534grgkmcfofvu1l5h0nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.theCity',
  );
}
